export const allUsers=[
  {
    id:1,
    name:"Bill",
    lastName:'Ross',
    citty:'Athens',
    passportNumber:135856
  },
  {
    id:2,
    name:"Elizabeth",
    lastName:'Tucker',
    citty:'Houston',
    passportNumber:956357
  },
  {
    id:3,
    name:"Dave",
    lastName:'Banks',
    citty:'Copenhagen',
    passportNumber:752145
  },
  {
    id:4,
    name:"Ricky",
    lastName:'Nguyen',
    citty:'Palermo',
    passportNumber:203658
  }
]
